name: CI/CD Tienda Perritos - Backend
on:
  push:
    branches: [ "deploy" ]
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push a ECR
        run: |
          cd backend
          docker build -t tienda-backend .
          docker tag tienda-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

      - name: Desplegar Backend via Frontend
        uses: appleboy/ssh-action@v1.0.3
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPO_URL_BACKEND: ${{ secrets.ECR_REPO_URL_BACKEND }}
          EC2_BACKEND_HOST: ${{ secrets.EC2_BACKEND_HOST }}
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: AWS_REGION,ECR_REGISTRY,ECR_REPO_URL_BACKEND,EC2_BACKEND_HOST
          script: |
            aws ecr get-login-password --region $AWS_REGION | \
              docker login --username AWS --password-stdin $ECR_REGISTRY
            docker pull $ECR_REPO_URL_BACKEND:latest
            docker save $ECR_REPO_URL_BACKEND:latest | \
              ssh -i ~/.ssh/Devops.pem \
                  -o StrictHostKeyChecking=no \
                  ec2-user@$EC2_BACKEND_HOST \
                  "docker load; \
                   docker stop tienda-backend || true; \
                   docker rm tienda-backend || true; \
                   docker run -d --name tienda-backend --restart always \
                   -p 3001:3001 $ECR_REPO_URL_BACKEND:latest"
